
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.octaldecimal;

/** CUP generated class containing symbol constants. */
public class SintaxisOctalSym {
  /* terminals */
  public static final int numero = 2;
  public static final int error = 1;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "numero"
  };
}

