
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.mycompany.octaldecimal;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class SintaxisOctal extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return SintaxisOctalSym.class;
}

  /** Default constructor. */
  @Deprecated
  public SintaxisOctal() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public SintaxisOctal(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public SintaxisOctal(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\004\000\002\002\004\000\002\003\004\000\002\003" +
    "\003\000\002\002\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\006\000\004\004\004\001\002\000\006\002\ufffe\004" +
    "\ufffe\001\002\000\006\002\uffff\004\uffff\001\002\000\006" +
    "\002\010\004\004\001\002\000\006\002\000\004\000\001" +
    "\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\006\000\006\002\004\003\005\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\002\006\001\001\000\002" +
    "\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$SintaxisOctal$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$SintaxisOctal$actions(this);
    }

  /** Invoke a user supplied parse action.
     * @param act_num
     * @param parser
     * @param stack
     * @param top
     * @return 
     * @throws java.lang.Exception */
 @Override
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$SintaxisOctal$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;
    
    public void syntax_error(Symbol s){
    }

    public void unrecovered_syntax_error(Symbol s) throws java.lang.Exception{
    }

    public Symbol getS(){
        return this.s;
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$SintaxisOctal$actions {
  private final SintaxisOctal parser;

  /** Constructor */
  CUP$SintaxisOctal$actions(SintaxisOctal parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$SintaxisOctal$do_action_part00000000(
    int                        CUP$SintaxisOctal$act_num,
    java_cup.runtime.lr_parser CUP$SintaxisOctal$parser,
    java.util.Stack            CUP$SintaxisOctal$stack,
    int                        CUP$SintaxisOctal$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$SintaxisOctal$result;

      /* select the action based on the action number */
      switch (CUP$SintaxisOctal$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= DECIMAL EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.elementAt(CUP$SintaxisOctal$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.elementAt(CUP$SintaxisOctal$top-1)).right;
		Integer start_val = (Integer)((java_cup.runtime.Symbol) CUP$SintaxisOctal$stack.elementAt(CUP$SintaxisOctal$top-1)).value;
		RESULT = start_val;
              CUP$SintaxisOctal$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.elementAt(CUP$SintaxisOctal$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$SintaxisOctal$parser.done_parsing();
          return CUP$SintaxisOctal$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // DECIMAL ::= DECIMAL OCTAL 
            {
              Integer RESULT =null;
		int d1left = ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.elementAt(CUP$SintaxisOctal$top-1)).left;
		int d1right = ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.elementAt(CUP$SintaxisOctal$top-1)).right;
		Integer d1 = (Integer)((java_cup.runtime.Symbol) CUP$SintaxisOctal$stack.elementAt(CUP$SintaxisOctal$top-1)).value;
		int e1left = ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.peek()).right;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$SintaxisOctal$stack.peek()).value;
		RESULT = (d1*8)+ e1;
              CUP$SintaxisOctal$result = parser.getSymbolFactory().newSymbol("DECIMAL",1, ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.elementAt(CUP$SintaxisOctal$top-1)), ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.peek()), RESULT);
            }
          return CUP$SintaxisOctal$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // DECIMAL ::= OCTAL 
            {
              Integer RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.peek()).right;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$SintaxisOctal$stack.peek()).value;
		RESULT = e1;
              CUP$SintaxisOctal$result = parser.getSymbolFactory().newSymbol("DECIMAL",1, ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.peek()), RESULT);
            }
          return CUP$SintaxisOctal$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // OCTAL ::= numero 
            {
              Integer RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.peek()).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.peek()).right;
		Integer e1 = (Integer)((java_cup.runtime.Symbol) CUP$SintaxisOctal$stack.peek()).value;
		RESULT = e1;
              CUP$SintaxisOctal$result = parser.getSymbolFactory().newSymbol("OCTAL",0, ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.peek()), ((java_cup.runtime.Symbol)CUP$SintaxisOctal$stack.peek()), RESULT);
            }
          return CUP$SintaxisOctal$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$SintaxisOctal$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$SintaxisOctal$do_action(
    int                        CUP$SintaxisOctal$act_num,
    java_cup.runtime.lr_parser CUP$SintaxisOctal$parser,
    java.util.Stack            CUP$SintaxisOctal$stack,
    int                        CUP$SintaxisOctal$top)
    throws java.lang.Exception
    {
              return CUP$SintaxisOctal$do_action_part00000000(
                               CUP$SintaxisOctal$act_num,
                               CUP$SintaxisOctal$parser,
                               CUP$SintaxisOctal$stack,
                               CUP$SintaxisOctal$top);
    }
}

}
